apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.data.service.fullname" . }} 
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "elasticsearch"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "elasticsearch"
    release: {{ .Release.Name | quote }}
    role: data