apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "elasticsearch.master.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    role: master
spec:
  replicas: {{ .Values.master.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch.name" . }}
        component: {{ .Values.name }}
        release: {{ .Release.Name }}
        role: master
      annotations:
      {{- if .Values.increaseMemMapLimit }}
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
      {{- end }}
    spec:
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: {{ .Values.image }}
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: {{ .Values.clusterName }}
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#split-brain
          # The number of minimum master nodes is set according to:
          # (master_eligible_nodes / 2) + 1
        - name: "NUMBER_OF_MASTERS"
          value: "{{ div .Values.master.replicas 2 | add1 }}"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        - name: "DISCOVERY_SERVICE"
          value: "{{ template "elasticsearch.discovery.fullname" . }}"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
