apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kibana.fullname" . }}
  labels:
    app: {{ template "kibana.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.name | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    kubernetes.io/cluster-service: "true"
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "kibana.fullname" . }}
        component: {{ .Values.name | quote }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: kibana-logging
        image: {{ .Values.image | quote }}
        resources:
          # keep request = limit to keep this container in guaranteed class
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP